### ISSUE TITLE
AO3 announcement banner replacing bio on user page

### ISSUE THREAD

**Issue by searchtools-avi** [ArmindoFlores/ao3_api#15]
using the example in the readme, the output is: 
```
https://archiveofourown.org/users/bothersomepotato

The Archive will be down for 2 hours of maintenance between 05:00-07:00 UTC on Thursday, October 1 (what time is that for me?). Please check @AO3_Status on Twitter for updates.

2
```
The HTML looks like this: 

```
  <div class="clear"></div>

</div>

  <div class="alert announcement group" id="admin-banner">
    <blockquote class="userstuff">
      <p>The Archive <b>will be down for 2 hours</b> of maintenance between <b>05:00-07:00 UTC on Thursday, October 1</b> (<a href="https://bit.ly/2Gjf2zA" rel="nofollow">what time is that for me?</a>). Please check <a href="https://twitter.com/AO3_Status" rel="nofollow">@AO3_Status on Twitter</a> for updates.</p>
    </blockquote>
      <form action="/users/username/end_banner" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="&#x2713;"/>
        <p class="submit">
          <input type="submit" name="commit" value="&times;" title="hide banner"/>
        </p>
</form>  </div>


<!-- END header -->
```
I think it can be fixed by adding this to the soup path `<div class="bio module">`

**Comment by ArmindoFlores** [comment]
The banner is gone so I can't replicate it but I'll change the expression it looks for to what you suggested

**Comment by ArmindoFlores** [comment]
Should be fixed now (I tried it with the International Fanworks Day banner)

**Comment by enigmalea** [comment]
I'm still getting the International Fanworks Day Banner on my attempts. Here is the {user.bio} populating in a discord embed.

![image](https://user-images.githubusercontent.com/73132777/107975408-0f6c7900-6f86-11eb-9ac2-c65cc8372fe4.png)

and here is the code I'm using to generate the embed's description:

`        desc = f"**Number of Works:** {user.works}\n**Number of Bookmarks:** {user.bookmarks}\n\n**Bio:**\n{user.bio}"`

**Comment by ArmindoFlores** [comment]
While it is fixed on github, the version oh pypi (2.0.6) doesn't have the fix implemented. If you need it ASAP, please clone the repo and install it using the setup.py.
